### ISSUE TITLE
Plans for support

### ISSUE THREAD

**Issue by michail-nikolaev** [akorotkov/jsquery#6]
Currently we are evaluating jsquery to be used in long-term project. So:

1) I known about http://obartunov.livejournal.com/179422.html but do you have any plans for supporting it? Updating to next (9.5) releases?

2) Could you advice any other solution which allows to store some kind of predicate for JSONB field as separated "object' (field, text, etc)

**Comment by akorotkov** [comment]
1) I suppose jsquery extension would require very small changes (if any) to support 9.5. Thus, yes, jsquery will support 9.5.
2) I didn't understood what exactly did you mean. Can you give some example?

**Comment by michail-nikolaev** [comment]
Thanks for answers.

We have to store some kind of "predicate" inside the database.

For example, we have some objects, each of them have some kind of predicate for user. For example, age > 30 && sex = w.

And we have set of users with jsonb field:
user {
   age: 40,
   sex: w
}

Everything is stored in DB. So, we can select all objects which allowed to be accessed by user:

select o.* from objects as o join users as u where us.id = 13 and u.data @@ o.predicate

**Comment by akorotkov** [comment]
You can store jsquery in the table column.

**Comment by michail-nikolaev** [comment]
@akorotkov yes, I expect that - and it is killer feature in our case.

Thanks for you help.

**Comment by akorotkov** [comment]
I have one more note about this. Currently you can't build GIN index on jsquery column so that search jsqueries which match particular jsonb values. However, it's potentially possible.
