### ISSUE TITLE
Support for PostgreSQL 9.5+

### ISSUE THREAD

**Issue by darkixion** [akorotkov/jsquery#7]
Currently getting this error when building against 9.5devel as CRC has been changed:

    jsquery_op.c:19:26: fatal error: utils/pg_crc.h: No such file or directory
     #include "utils/pg_crc.h"
                              ^

Could this be updated to support 9.5?

**Comment by feodor** [comment]
Thank you, fixed

**Comment by NikolayS** [comment]
:thumbsup:
